# -*- encoding: utf-8 -*-
$:.push File.expand_path("../lib", __FILE__)
require "insika/version"

Gem::Specification.new do |s|
  s.name        = "insika"
  s.version     = Insika::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Red (E) Tools Ltd."]
  s.email       = ["office@thebigrede.net"]
  s.homepage    = "http://thebigrede.net"
  s.summary     = %q{Convenient API for the INSIKA TIM}
  s.description = %q{The INSIKA system is based on digital signatures generated by a smart card to secure sales data against fraudulent manipulation.}

  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.require_paths = ["lib"]
  
  s.add_dependency("rubyzip", "0.9.9")
  s.add_dependency("smartcard", "0.5.5")
end
